import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { marketAnalysisData, etfBuySellData } from '../data/reportData';

export const generateDailyReport = (todaysRankings: any[]) => {
    const doc = new jsPDF();
    const today = new Date().toISOString().split('T')[0];

    // -- Cover Page --
    doc.setFontSize(24);
    doc.text("ETF Momentum Daily Report", 105, 100, { align: "center" });

    doc.setFontSize(16);
    doc.text(`Date: ${today}`, 105, 115, { align: "center" });

    doc.setFontSize(12);
    doc.text("Generated by ETF Momentum Algo", 105, 125, { align: "center" });
    doc.text("confidential - for admin use only", 105, 135, { align: "center" });

    doc.addPage();

    // -- Chapter 1: Market Analysis --
    doc.setFontSize(18);
    doc.text("1. Daily Market Analysis", 14, 20);

    doc.setFontSize(12);
    doc.text(`Fear & Greed: ${marketAnalysisData.sentimentMacro.fearGreedIndex.value} (${marketAnalysisData.sentimentMacro.fearGreedIndex.status})`, 14, 30);
    doc.text(`Put/Call Ratio: ${marketAnalysisData.sentimentMacro.putCallRatio.value}`, 14, 38);

    doc.text("Global Liquidity Overview:", 14, 50);
    const liquidityText = doc.splitTextToSize(marketAnalysisData.globalLiquidity.sectorRotation, 180);
    doc.text(liquidityText, 14, 58);

    doc.text("Final Verdict:", 14, 80);
    doc.setFontSize(14);
    doc.setTextColor(220, 38, 38); // Red
    doc.text(marketAnalysisData.finalVerdict.status, 14, 90);
    doc.setTextColor(0, 0, 0); // Black

    // -- Chapter 2: Top ETF Rankings --
    doc.addPage();
    doc.setFontSize(18);
    doc.text("2. ETF Ranking Top List", 14, 20);

    const rankingRows = todaysRankings.slice(0, 30).map(item => [
        item.rank,
        item.name,
        item.nowPrice,
        item.fluctuationRate
    ]);

    autoTable(doc, {
        head: [['Rank', 'ETF Name', 'Price', 'Change']],
        body: rankingRows,
        startY: 30,
        styles: { font: "helvetica" },
    });

    // -- Chapter 3: Strategy Proposals --
    doc.addPage();
    doc.setFontSize(18);
    doc.text("3. AI Trade Proposals", 14, 20);

    let yPos = 30;
    etfBuySellData.forEach((etf) => {
        if (yPos > 250) {
            doc.addPage();
            yPos = 20;
        }

        doc.setFontSize(14);
        doc.setTextColor(37, 99, 235);
        doc.text(`[${etf.action}] ${etf.name}`, 14, yPos);
        yPos += 8;

        doc.setFontSize(10);
        doc.setTextColor(0);
        // Using 'rank' from string to just text
        doc.text(`Rank: ${etf.rank}`, 14, yPos);
        yPos += 6;

        doc.text(`Target: ${etf.strategy.goal} / Cut: ${etf.strategy.stop}`, 14, yPos);
        yPos += 6;

        const thesis = doc.splitTextToSize(`Thesis: ${etf.fundamental.thesis}`, 180);
        doc.text(thesis, 14, yPos);
        yPos += thesis.length * 5 + 10;
    });

    // Save
    doc.save(`ETF_Report_${today}.pdf`);
};
